# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # define filters defined in pentatrion_upload.liip_filters
    filter_sets:
        small:
            filters:
                thumbnail:
                    { size: [250, 250], mode: inset, allow_upscale: true }

        large:
            filters:
                thumbnail:
                    { size: [1500, 1500], mode: inset, allow_upscale: false }

    loaders:
        default:
            filesystem:
                data_root:
                    # must be linked with pentatrion_upload -> liip_path
                    - "%kernel.project_dir%/public"
