pentatrion_upload:
    # default configuration
    file_infos_helper: 'Pentatrion\UploadBundle\Service\FileInfosHelper'
    origins:
        public_uploads:
            path: "%kernel.project_dir%/public/uploads"
            liip_path: "/uploads"
    liip_filters: ["small"]
