twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        themes: '%env(json:THEMES)%'
    form_themes:
        - 'form/custom_types.html.twig'
when@test:
    twig:
        strict_variables: true
